from .categorize import CATEGORIZE_EMAIL_PROMPT
from .proofreader import EMAIL_PROOFREADER_PROMPT
from .rag import GENERATE_RAG_ANSWER_PROMPT, GENERATE_RAG_QUERIES_PROMPT
from .writer import EMAIL_WRITER_PROMPT


__all__ = [
    "CATEGORIZE_EMAIL_PROMPT",
    "EMAIL_PROOFREADER_PROMPT",
    "EMAIL_WRITER_PROMPT",
    "GENERATE_RAG_ANSWER_PROMPT",
    "GENERATE_RAG_QUERIES_PROMPT",
]
